name: Terraform Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Hent secrets fra Key Vault
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "RESOURCE_GROUP_TEST=$(az keyvault secret show --vault-name kvpp001 --name test-resourcegroupname --query value -o tsv)" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_TEST=$(az keyvault secret show --vault-name kvpp001 --name test-storageaccountname --query value -o tsv)" >> $GITHUB_ENV
          echo "LOCATION_TEST=$(az keyvault secret show --vault-name kvpp001 --name test-location --query value -o tsv)" >> $GITHUB_ENV
          echo "ENVIRONMENT_TEST=$(az keyvault secret show --vault-name kvpp001 --name test-environment --query value -o tsv)" >> $GITHUB_ENV
          echo "RESOURCE_GROUP_DEV=$(az keyvault secret show --vault-name kvpp001 --name dev-resourcegroupname --query value -o tsv)" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_DEV=$(az keyvault secret show --vault-name kvpp001 --name dev-storageaccountname --query value -o tsv)" >> $GITHUB_ENV
          echo "LOCATION_DEV=$(az keyvault secret show --vault-name kvpp001 --name dev-location --query value -o tsv)" >> $GITHUB_ENV
          echo "ENVIRONMENT_DEV=$(az keyvault secret show --vault-name kvpp001 --name dev-environment --query value -o tsv)" >> $GITHUB_ENV
          echo "RESOURCE_GROUP_PROD=$(az keyvault secret show --vault-name kvpp001 --name prod-resourcegroupname --query value -o tsv)" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_PROD=$(az keyvault secret show --vault-name kvpp001 --name prod-storageaccountname --query value -o tsv)" >> $GITHUB_ENV
          echo "LOCATION_PROD=$(az keyvault secret show --vault-name kvpp001 --name prod-location --query value -o tsv)" >> $GITHUB_ENV
          echo "ENVIRONMENT_PROD=$(az keyvault secret show --vault-name kvpp001 --name prod-environment --query value -o tsv)" >> $GITHUB_ENV
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          -var="resource_group_name=${{ env.RESOURCE_GROUP }}" \
          -var="location=${{ env.LOCATION }}" \
          -var="app_service_name=${{ env.APP_NAME }}"
